@apiUrl = http://{CRESTRON_API_HOST}/cws/api
@authToken = {CRESTRON_API_AUTH_TOKEN}

@openValue = 65535

### Ping
# @name ping
GET {{apiUrl}}

### login
# @name login
GET {{apiUrl}}/login
Crestron-RestAPI-AuthToken: {{authToken}}

### DEVICES ----------------------------------------------

### List devices
# @name listDevices
GET {{apiUrl}}/devices
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}

### Get device
# @name getDevice
GET {{apiUrl}}/devices/{{listDevices.response.body.devices[0].id}}
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}

### SHADES ----------------------------------------------

### List shades
# @name listShades
GET {{apiUrl}}/shades
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}

### Get shade
# @name getShade
GET {{apiUrl}}/shades/{{listShades.response.body.shades[0].id}}
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}


### Open shades
# @name openShades
POST {{apiUrl}}/shades/setstate
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}
Content-Type: application/json

{
  "shades": [
    {
      "position": {{openValue}},
      "id": 1,
      "name": "Door Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 2
    },
    {
      "position": {{openValue}},
      "id": 2,
      "name": "Window Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 2
    },
    {
      "position": {{openValue}},
      "id": 3,
      "name": "Front Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 1
    }
  ]
}


### Close shades
# @name closeShades
POST {{apiUrl}}/shades/setstate
Crestron-RestAPI-AuthKey: {{login.response.body.authkey}}
Content-Type: application/json

{
  "shades": [
    {
      "position": 0,
      "id": 1,
      "name": "Door Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 2
    },
    {
      "position": 0,
      "id": 2,
      "name": "Window Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 2
    },
    {
      "position": 0,
      "id": 3,
      "name": "Front Shade",
      "subType": "Shade",
      "connectionStatus": "online",
      "roomId": 1
    }
  ]
}

### -----------------------------------------------------